### ISSUE TITLE
Type sensor

### ISSUE THREAD

**Issue by RFGA** [HackerInside0/Arduino_SharpIR#4]
Dear, I would like to know if the GP2YA41SK0F type really is valid or not. Because I didn't find this type (eg at https://www.pololu.com/). I think the correct is the GP2Y0A41SK0F.

**Comment by qub1750ul** [comment]
Currently GP2YA41SK0F is a valid sensor type in the library.
But effectively that's a typo, as you correctly noted.
I will correct this asap with a major release.

**Comment by qub1750ul** [comment]
Fixed in v2.0.0
Now GP2Y0A41SK0F is the valid sensor type.
